{
ID                  => 'US_CDL',
Comment		    => 'CONUS simulation with CDL crops and soil moisture drying function applied',
Project		    => 'PCHES',
MT_Code_Name	    =>  {
          MT_ID     => 'US_CDL',
          Output_dir => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/wbm_output',
          Run_Start => '2007-01-01',
          Run_End   => '2022-12-31'
          },

Spinup => {
	Loops		=> '0',
	State_ID	=> 'US_CDL_S'
},


Output_vars	    =>  'soilMoistFrac
                         soilMoist',
			 
MT_Precip	    => { Primary   => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/gridMET_ppt_4kmD2_d.init'},
precipFraction	    => '',
MT_airT	            => { Primary   => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/gridMET_tmean_4kmD2_d.init'},
Network	            => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data/network/Network6.asc',
Projection	    => 'epsg:4326',
Routing	            => 'LRR',
wbmParam	    => {scrPrintScale => 1e-2,
                            alpha => 5},
ConnectivityNetwork => '',
Reservoirs	    => '',

#soilAWCapacity	    => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data/soil/SSURGO_SoilData_awc_frac_mm_m_CONUS_1km.tif',
soilAWCapacity	    => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/AWC.init',

MT_cloudFr          => { Primary => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra2_cldtot_d.init'},

#MT_windU            => { Primary => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra2_u10m_d.init'},
#MT_windV            => { Primary => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra2_v10m_d.init'},
MT_windU            => { Primary => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/gridMET_u10m_d.init'},
MT_windV            => { Primary => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/gridMET_v10m_d.init'},
canopyHt            => '/gpfs/group/kaf26/default/private/WBM_data/squam.sr.unh.edu/US_CDL_v3_data/canopy/Simard_Pinto_3DGlobalVeg_JGR_10km.tif',
MT_humidity      => { Primary => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/gridMET_rh2m_d.init'},
#MT_relHumidity      => { Primary => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra2_rh2m_d.init'},
MT_albedo           => { Primary => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra_albedo_dc.init' },
airT_yc             => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra2_t2m_yc.init',
MT_LAI              => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra2_lai2_dc.init',
####
#PET                 => 'Hamon',
PET                 => 'Penman-Monteith',
FieldCap	    => '',
WiltingPoint	    => '',
#rootingDepth        => 'NETCDF:/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data/soil/Global_Terrain_RootDepthWBM_LTXXXX_30min.nc:STNetwork',
rootingDepth        => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/rootdepth.init',
PET_Factor	    => '',
openWaterEvap	    => '',
Glaciers	    => '',
snowBands	    => 0,
lapseDownscale	    => '',
DIN                 => '',
Runoff_mask	    => '',
Impervious	    => '',
openWater	    => '',
WaterDemand	    => '',
landCollapse	    => '',
LandCover	    => '',
Irrigation	    => {
                    CropAreaFrac  => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/TotalCropland.init',
                    CropAreaFracPatch => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/mirca_cropAreaFraction.init',

                    IrrEfficiency => 'NETCDF:/gpfs/group/kaf26/default/private/WBM_data/squam.sr.unh.edu/US_CDL_v3_data/crops/Global_Crops_IrrEfficiencyGlobalExtent_30min.nc:IrrEfficiency',
                    CropParFile   => '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/CropParameters.csv',
                    Order 	=> 1,
                    NoGrowth    => 1,
                    ReturnCoeff   => 0.5,
                    SearchDist    => 30,
                    ExtraCoeff    => 1,
	            IrrAreaGrwth  => 0,
	            CrpAreaGrwth  => 0,
                crpGrwthRefYr => 0,
                irrGrwthRefYr => 0,
                    extendCropTS  => 1,
		    dailyIrr	  => 0,
		    useVIS	  => 0,
                    ricePercolation => 'NETCDF:/gpfs/group/kaf26/default/private/WBM_data/squam.sr.unh.edu/US_CDL_v3_data/crops/RicePercolationRate.nc:RicePercolationRate',
                    ricePaddyDepth => 50},
#WaterRights 	    => '',
WM_mod_precip	    => '',
WM_obs_precip	    => '',
WM_mod_airT	    => '',
WM_obs_airT	    => '',
PostProcessing	    =>  {
                    Forks 		 => 8,
                    Polygon_Aggregation  => '',
                    Run 	           => 0,
                    TA_multi_year_start    => '',
                    TA_multi_year_timestep => '',
                    Temporal_Aggregation   => 1
                    }


}
