{
Code_Name	=> 'CDL-US-M_rice_irr_Kc_av',
Time_Series	=> 'daily',
Start_Date	=> '2009-01-01',
End_Date	=> '2016-12-31',
Name		=> 'CDL-US - crop climatology',
Var_Name	=> 'MC_rice_irr_Kc_av',
Units		=> 'unitless',
Var_Scale	=> 1,
Var_Offset	=> 0,
Orig_Units	=> 'unitless',
Bands		=> 365,
Processing	=> '',
Projection	=> 'epsg:4326',
File_Path	=> '/gpfs/group/kaf26/default/private/WBM_data/squam.sr.unh.edu/US_CDL_v3_data/crops/MIRCA_CDL-US-M/Kc_av/_YEAR_/MC_rice_irr_Kc_av.nc'
}
