{
Code_Name	=> 'gridMET_ppt_4kmD2_d',
Time_Series	=> 'daily',
Start_Date	=> '2007-01-01',
End_Date	=> '2022-12-31',
Name		=> 'gridMET, US 4 km, Daily Accumulated Precipitation, Daily',
Var_Name	=> 'precipitation_amount',
Units		=> 'mm/day',
Var_Scale	=> 1,
Var_Offset	=> 0,
Orig_Units	=> 'mm/day',
Bands		=> 366,
Processing	=> '32767',
Projection	=> 'epsg:4326',
File_Path	=> '(1e20,1e4):/gpfs/group/kaf26/default/private/WBM_data/Metdata_2008_2022/pr__YEAR_.nc;'
}
