{
Code_Name	=> 'MC_rfd_Kc_av',
Time_Series	=> 'daily_clim',
Start_Date	=> '0000-01-01',
End_Date	=> '0000-12-31',
Var_Name	=> 'MC_rfd_Kc_av',
Units	=> 'unitless',
Var_Scale	=> 1,
Var_Offset	=> 0,
Orig_Units	=> 'unitless',
Bands   => 365,
Processing	=> '',
Projection	=> 'epsg:4326',
File_Path	=> '/gpfs/group/kaf26/default/private/WBM_data/squam.sr.unh.edu/US_CDL_v3_data/crops/MIRCA/Kc_av/MC_rfd_Kc_av.nc',
Comment => 'Metadata at above path.'
}
