{
ID		=> 'US_CDL',
Comment		=> 'CONUS simulation with CDL crops and soil moisture drying function applied',
Project		=> 'PCHES',
MT_Code_Name	=>  {
          MT_ID		=> 'US_CDL',
          Output_dir	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/wbm_output',
          Run_End	=> '2022-12-31',
          Run_Start	=> '2007-01-01'
        },
Spinup		=>  {
          End		=> '',
          Force_ID_Date	=> '',
          Loops		=> '0',
          Save_Vars	=> '',
          Start		=> '',
          State_ID	=> 'US_CDL_S'
        },
Output_vars	=> 'soilMoistFrac soilMoist',
MT_Precip	=>  {
          Primary	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/gridMET_ppt_4kmD2_d.init'
        },
precipFraction	=> '',
MT_airT		=>  {
          Primary	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/gridMET_tmean_4kmD2_d.init'
        },
Network		=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data/network/Network6.asc',
Projection	=> 'epsg:4326',
Routing		=> 'LRR',
wbmParam	=>  {
          alpha		=> 5,
          scrPrintScale	=> '0.01'
        },
ConnectivityNetwork	=> '',
Reservoirs	=> '',
soilAWCapacity	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/AWC.init',
FieldCap	=> '',
WiltingPoint	=> '',
rootingDepth	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/rootdepth.init',
PET		=> 'Penman-Monteith',
MT_windU	=>  {
          Primary	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/gridMET_u10m_d.init'
        },
MT_windV	=>  {
          Primary	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/gridMET_v10m_d.init'
        },
MT_cloudFr	=>  {
          Primary	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra2_cldtot_d.init'
        },
MT_humidity	=>  {
          Primary	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/gridMET_rh2m_d.init'
        },
MT_albedo	=>  {
          Primary	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra_albedo_dc.init'
        },
airT_yc		=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra2_t2m_yc.init',
openWaterEvap	=> '',
Glaciers	=> '',
Aquifers	=> '',
Springs		=> '',
snowBands	=> 0,
lapseDownscale	=> '',
DIN		=> '',
Runoff_mask	=> '',
Impervious	=> '',
openWater	=> '',
canopyHt	=> '/gpfs/group/kaf26/default/private/WBM_data/squam.sr.unh.edu/US_CDL_v3_data/canopy/Simard_Pinto_3DGlobalVeg_JGR_10km.tif',
MT_LAI		=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/merra2_lai2_dc.init',
WaterDemand	=> '',
landCollapse	=> '',
LandCover	=> '',
Irrigation	=>  {
          CropAreaFrac	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/TotalCropland.init',
          CropAreaFracPatch	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/mirca_cropAreaFraction.init',
          CropParFile	=> '/gpfs/group/kaf26/default/users/aqa6478/WBM/SM_Main/data_init/CropParameters.csv',
          CrpAreaGrwth	=> 0,
          ExtraCoeff	=> 1,
          IrrAreaGrwth	=> 0,
          IrrEfficiency	=> 'NETCDF:/gpfs/group/kaf26/default/private/WBM_data/squam.sr.unh.edu/US_CDL_v3_data/crops/Global_Crops_IrrEfficiencyGlobalExtent_30min.nc:IrrEfficiency',
          NoGrowth	=> 1,
          Order		=> 1,
          ReturnCoeff	=> '0.5',
          SearchDist	=> 30,
          crpGrwthRefYr	=> 0,
          dailyIrr	=> 0,
          extendCropTS	=> 1,
          irrGrwthRefYr	=> 0,
          ricePaddyDepth	=> 50,
          ricePercolation	=> 'NETCDF:/gpfs/group/kaf26/default/private/WBM_data/squam.sr.unh.edu/US_CDL_v3_data/crops/RicePercolationRate.nc:RicePercolationRate',
          useVIS	=> 0
        },
WM_mod_precip	=> '',
WM_obs_precip	=> '',
WM_mod_airT	=> '',
WM_obs_airT	=> '',
PostProcessing	=>  {
          Forks		=> 8,
          Polygon_Aggregation	=> '',
          Run		=> 0,
          TA_multi_year_start	=> '',
          TA_multi_year_timestep	=> '',
          Temporal_Aggregation	=> 1
        },
WaterRights	=> '',
USGS		=> ''
}
